services:
  angular-app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: seo-content-app-dev
    volumes:
      - ./:/app/
      - /app/node_modules
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - CHROME_BIN=/usr/bin/chromium-browser
    command: npx ng serve --host 0.0.0.0 --poll 2000
    stdin_open: true
    tty: true
