FROM node:20-alpine

WORKDIR /app

RUN apk add \
    g++ \
    git \
    make \
    python3 \
    --no-cache

COPY package*.json ./

RUN npm install

EXPOSE 4200

CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--poll", "2000"]
