FROM node:20-alpine

WORKDIR /app

RUN npm install -g @angular/cli@17

RUN apk add --no-cache \
    python3 \
    make \
    g++

COPY package*.json ./

RUN npm install

EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0", "--poll", "2000"]
