FROM node:20-alpine

WORKDIR /app

RUN apk add \
    chromium \
    g++ \
    git \
    make \
    openssh \
    python3 \
    --no-cache

ENV CHROME_BIN=/usr/bin/chromium-browser

COPY package*.json ./

RUN npm install

EXPOSE 4200

CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--poll", "2000"]
