#!/bin/bash
# Sets up the Claude Code Chrome extension inside the devcontainer.
# Downloads the extension CRX, extracts it as an unpacked extension,
# creates the native messaging host script, and registers the manifests.
set -e

EXTENSION_ID="fcoeoabgfenejglbffodgkkbkcdhcgfn"
EXTENSION_DIR="$HOME/.chrome-extensions/$EXTENSION_ID"
NATIVE_HOST_DIR="$HOME/.claude/chrome"
NATIVE_HOST_SCRIPT="$NATIVE_HOST_DIR/chrome-native-host"

echo "=== Claude Chrome Extension Setup ==="

# --- Download and extract extension ---
if [ -d "$EXTENSION_DIR" ] && [ -f "$EXTENSION_DIR/manifest.json" ]; then
  echo "Extension already installed at $EXTENSION_DIR"
else
  echo "Downloading Claude Chrome extension from Web Store..."
  mkdir -p /tmp/crx-work

  CRX_URL="https://clients2.google.com/service/update2/crx?response=redirect&prodversion=120.0.0.0&acceptformat=crx3&x=id%3D${EXTENSION_ID}%26uc"
  curl -sL \
    -A "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" \
    -o /tmp/crx-work/extension.crx \
    "$CRX_URL"

  python3 <<'PYTHON'
import struct, zipfile, io, sys, shutil, os

crx_path = '/tmp/crx-work/extension.crx'
extract_path = '/tmp/crx-work/unpacked'
dest = os.path.expanduser('~') + '/.chrome-extensions/fcoeoabgfenejglbffodgkkbkcdhcgfn'

with open(crx_path, 'rb') as f:
    magic = f.read(4)
    if magic != b'Cr24':
        sys.exit(f'ERROR: Not a valid CRX file (magic={magic!r}). Download may have failed.')
    version = struct.unpack('<I', f.read(4))[0]
    if version == 3:
        header_size = struct.unpack('<I', f.read(4))[0]
        f.seek(12 + header_size)
    else:  # CRX2
        pub_len = struct.unpack('<I', f.read(4))[0]
        sig_len = struct.unpack('<I', f.read(4))[0]
        f.seek(16 + pub_len + sig_len)
    zip_data = f.read()

os.makedirs(extract_path, exist_ok=True)
with zipfile.ZipFile(io.BytesIO(zip_data)) as z:
    z.extractall(extract_path)

if os.path.exists(dest):
    shutil.rmtree(dest)
os.makedirs(os.path.dirname(dest), exist_ok=True)
shutil.copytree(extract_path, dest)
print(f'Extension extracted to {dest}')
PYTHON

  rm -rf /tmp/crx-work
  echo "Extension downloaded and extracted."
fi

# --- Create native messaging host script ---
mkdir -p "$NATIVE_HOST_DIR"

if [ ! -f "$NATIVE_HOST_SCRIPT" ]; then
  NODE_BIN=$(which node)
  CLAUDE_CLI="/usr/local/lib/node_modules/@anthropic-ai/claude-code/cli.js"
  cat > "$NATIVE_HOST_SCRIPT" <<EOF
#!/bin/sh
# Chrome native host wrapper script
# Generated by setup-claude-chrome.sh
exec "$NODE_BIN" "$CLAUDE_CLI" --chrome-native-host
EOF
  chmod +x "$NATIVE_HOST_SCRIPT"
  echo "Native host script created at $NATIVE_HOST_SCRIPT"
fi

# --- Register native messaging host manifests ---
MANIFEST_CONTENT=$(cat <<EOF
{
  "name": "com.anthropic.claude_code_browser_extension",
  "description": "Claude Code Browser Extension Native Host",
  "path": "$NATIVE_HOST_SCRIPT",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://$EXTENSION_ID/"
  ]
}
EOF
)

for CONFIG_DIR in \
  "$HOME/.config/chromium" \
  "$HOME/.config/google-chrome" \
  "$HOME/.config/microsoft-edge"; do
  MANIFEST_DIR="$CONFIG_DIR/NativeMessagingHosts"
  mkdir -p "$MANIFEST_DIR"
  echo "$MANIFEST_CONTENT" > "$MANIFEST_DIR/com.anthropic.claude_code_browser_extension.json"
done

echo "Native messaging host manifests registered."
echo ""
echo "=== Setup complete! ==="
echo "Run 'bash /app/docker/start-claude-chrome.sh' to launch Chromium with the extension."
